# Generated by Django 6.0.3 on 2026-04-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
